messages:
  no-perm: '&e&lPTP &7You do not have permission for this action'
  only-in-game: '&e&lPTP &7This command is only for players'
  invalid-block: '&e&lPTP &7Invalid block'
  invalid-string: '&e&lPTP &7Invalid string'
  teleporter-created: '&e&lPTP &7Teleporter &a%name% created. Don''t forget to set its location with &a/ptp setloc %name%'
  already-exists: '&e&lPTP &7A teleporter with the same name already exists'
  teleporter-not-found: '&e&lPTP &7Teleporter not found'
  location-set: '&e&lPTP &7Location for &a%teleporter% &7is set'
  deleted: '&e&lPTP &a%teleporter% &7is deleted'
  create-usage: '&e&lPTP &7/ptp create &a<name>'
  setsound-usage: '&e&lPTP &7/ptp setsound &a<name> <sound>'
  setlocation-usage: '&e&lPTP &7/ptp setlocation &a<name>'
  delete-usage: '&e&lPTP &7/ptp delete &a<name>'
  invalid-sound: '&e&lPTP &7Invalid sound'
  sound-set: '&e&lPTP &7Sound set'
  permission-set: '&e&lPTP &7Permission &a%permission% &7is set for &a%teleporter%'
  set-permission-usage: '&e&lPTP &7/ptp setpermission &a<teleporter> <permission>'
  no-perm-teleporter: '&e&lPTP &7You do not have permission to use this teleporter'
  commands:
    - '&e&lPTP &7by #fb330et#fb4115h#fc501de#fc5e24l#fc6c2be#fc7a32g#fd893ae#fd9741n#fda548d'
    - '&7/ptp create &a<name> &fTo create a teleporter, look at a block while you submit.'
    - '&7/ptp setloc &a<name> &fTo link a location to the teleporter you created.'
    - '&7/ptp setsound &a<name> &fTo set a sound to a teleporter'
    - '&7/ptp setpermission &a<name> <permission> &fTo set a permission for this teleporter. Use ''none'' to remove the permission.'
    - '&7/ptp delete &a<name> &fTo delete a teleporter.'